name: Terraform Init and Apply

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
  push:
    branches-ignore:
      - main   #### Change to production 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: "aws_creds"
        name: "Configure Access & Secret keys"
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: "eu-central-1"
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.4.5

      - name: Terraform Init
        run: terraform -chdir=terraform init
        id: init-infra
        
      - name: Terraform Apply
        run: terraform -chdir=terraform apply --auto-approve -input=false
        id: deploy-infra


      - name: Terraform Destroy
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy-cluster' }}
        run: terraform -chdir=terraform destroy --auto-approve -input=false
        id: destroy-infra

      
